/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package webserver.app;

import webserver.config.Configuration;
import webserver.config.ConfigurationManager;

public class HttpServer {
    public static void main(String[] args) {
        System.out.println("Server starting...");

        ConfigurationManager.getInstance().loadConfigurationFile("app/src/main/resources/http.json");
        Configuration conf = ConfigurationManager.getInstance().getCurrentConfiguration();

        System.out.println("using port: " + conf.getPort());
        System.out.println("using webroot: " + conf.getWebroot());
    }
}
