/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    application
    id("webserver.java-application-conventions")
}

group = "webserver.app"
version = "1.0-SNAPSHOT"
val junitVersion = "5.9.2"
val javaLanguageVersion = 17

repositories {
    mavenCentral()
}

dependencies {
    testImplementation("org.junit.jupiter:junit-jupiter-api:${junitVersion}")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:${junitVersion}")
    testImplementation("org.junit.jupiter:junit-jupiter-params:${junitVersion}")
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(javaLanguageVersion))
    }
}

application {
    // Define the main class for the application.
    mainClass.set("webserver.app.App")
}

tasks.getByName<Test>("test") {
    useJUnitPlatform()
}
